### ISSUE TITLE
Unable to see logs, getting connection errors

### ISSUE THREAD

**Issue by thoefkens** [localstack/localstack-desktop#10]
Hi all,

I have LocalStack Desktop launched with the localstack-pro:latest image.
However, I am unable to connect with the "terminal/shell" icon to my container, and getting this error:
We were unable to reach the endpoint. Please make sure container is up and running.

I am running the container with a trial license and have put in the auth key before launching the container.

<img width="1494" alt="image" src="https://github.com/localstack/localstack-desktop/assets/97980582/0b09d9b7-d555-4535-9722-7810faa7520c">

What may be the issue?

I have already tried recreating the container or restarting and recreating.

Thanks
Thomas

**Comment by thoefkens** [comment]
Btw found out that if I change the settings default endpoint URL from localhost.localstack.cloud to localhost only, I can access the container shell via localstack desktop

**Comment by Pive01** [comment]
Hi @thoefkens , thanks for the report.
Could you provide a bit more info on your setup? In particular:
1. which os are your running on? (If windows specify if you use WSL)
2. what are the configurations that you are providing for the container? In other words, what environment variables are you passing to the container?
The warning you see it means that when LS desktop tries to ping that endpoint it does not receive the expected response; this might be because either the port that is pinging is not the correct ones (4566 in this case which is the default), or there are some strange setting in the container network that might prevent this

**Comment by Pive01** [comment]
Closing since it's been stale for a while, if any more info comes up again feel free to re-open the issue
