### ISSUE TITLE
FIFO Queue cannot be created in SQS

### ISSUE THREAD

**Issue by penguinlab** [localstack/localstack-desktop#15]
If a name is entered in name, e.g. example.fifo, and it is created, it is rejected by the input check.

**Comment by Pive01** [comment]
Hi @penguinlab thanks for submitting your issue.
When dealing with SQS queues you need to specify in the attributes that the queue is fifo, otherwise the input will be rejected. This behavior is in parity with the one from AWS.
If you click on the "attributes" tab when creating a new queue it will expand the documentation where you can read

"FifoQueue – Designates a queue as FIFO. Valid values are true and false. If you don't specify the FifoQueue attribute, Amazon SQS creates a standard queue. You can provide this attribute only during queue creation. You can't change it for an existing queue. When you set this attribute, you must also provide the MessageGroupId for your messages explicitly. For more information, see [FIFO queue logic](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues-understanding-logic.html) in the Amazon SQS Developer Guide."

![image](https://github.com/user-attachments/assets/130aa603-638d-4f27-9b9c-c468276f16d1)


In the end an input of this type will allow you to create a fifo queue 
![image](https://github.com/user-attachments/assets/84c03983-474b-46b9-8aec-751a4591bbe7)
